import json
import os
from web3 import Web3
from solcx import compile_standard, install_solc

try:
    install_solc('0.8.0')
except Exception as e:
    pass

ganache_url = os.getenv("GANACHE_URL", "http://127.0.0.1:7545")
w3 = Web3(Web3.HTTPProvider(ganache_url))
if not w3.is_connected():
    print(f"❌ Error: Could not connect to Blockchain at {ganache_url}")
    print("   - Make sure Ganache is running.")
    print("   - If using a remote node, set 'GANACHE_URL' environment variable.")
    exit(1)

w3.eth.default_account = w3.eth.accounts[0]

def deploy_contract(file_path, contract_name):
    print(f"Deploying {contract_name} from {file_path}...")
    with open(file_path, "r") as f:
        source = f.read()

    compiled = compile_standard(
        {
            "language": "Solidity",
            "sources": {file_path: {"content": source}},
            "settings": {"outputSelection": {"*": {"*": ["abi", "evm.bytecode"]}}},
        },
        solc_version="0.8.0",
    )
    
    # Extract ABI and Bytecode
    # Note: solc output keys include the full path
    contract_interface = compiled["contracts"][file_path][contract_name]
    bytecode = contract_interface["evm"]["bytecode"]["object"]
    abi = contract_interface["abi"]

    Contract = w3.eth.contract(abi=abi, bytecode=bytecode)
    tx_hash = Contract.constructor().transact()
    tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    
    print(f"{contract_name} Deployed at: {tx_receipt.contractAddress}")
    return tx_receipt.contractAddress, abi

def main():
    # Deploy C&F (MedicineTracker)
    addr_cnf, abi_cnf = deploy_contract("sol/C&F.sol", "MedicineTracker")
    
    # Deploy Distributor
    addr_dist, abi_dist = deploy_contract("sol/distributor.sol", "DistributorRegistry")
    
    # Deploy Retailer
    addr_ret, abi_ret = deploy_contract("sol/retailer.sol", "RetailerRegistry")

    # Save Config
    # We use repr() instead of json.dumps() so that booleans are written as True/False (Python)
    # instead of true/false (JSON), guarding against NameError.
    
    config = f"""# Auto-generated by deploy_user_contracts.py

RPC_URL = "{ganache_url}"

# C&F / Tracker
ADDR_TRACKER = "{addr_cnf}"
ABI_TRACKER = {repr(abi_cnf)}

# Distributor
ADDR_DISTRIBUTOR = "{addr_dist}"
ABI_DISTRIBUTOR = {repr(abi_dist)}

# Retailer
ADDR_RETAILER = "{addr_ret}"
ABI_RETAILER = {repr(abi_ret)}
"""
    with open("app/blockchain_config.py", "w") as f:
        f.write(config)
    print("Configuration Saved.")

if __name__ == "__main__":
    main()
